import React from 'react';
import { ChatBubbleLeftRightIcon } from '@heroicons/react/24/outline';

const ExplanationSection = ({ label, content }) => (
  <div className="space-y-2 rounded-2xl border border-primary/10 bg-background/60 p-4">
    <p className="text-xs font-semibold uppercase tracking-[0.2em] text-text/50">{label}</p>
    <p className="text-sm leading-relaxed text-text/70">{content || '—'}</p>
  </div>
);

const ExplanationSummary = ({ summary }) => {
  if (!summary) {
    return (
      <div className="rounded-3xl border border-dashed border-primary/20 bg-white p-6 text-sm text-text/60 shadow-sm">
        Nemotron reasoning not generated yet. Trigger the XAI pipeline to fetch explanations.
      </div>
    );
  }

  return (
    <section className="rounded-3xl border border-primary/10 bg-white p-6 shadow-sm">
      <header className="flex items-center gap-3">
        <span className="inline-flex h-10 w-10 items-center justify-center rounded-full bg-primary/10 text-primary">
          <ChatBubbleLeftRightIcon className="h-5 w-5" />
        </span>
        <div>
          <h2 className="text-lg font-semibold text-primary">Narrative explanations</h2>
          <p className="text-xs text-text/50">Generated by Nemotron for investigators, judges, and technical reviewers.</p>
        </div>
      </header>

      <div className="mt-6 grid gap-4 lg:grid-cols-3">
        <ExplanationSection label="Investigator summary" content={summary.investigator_summary} />
        <ExplanationSection label="Judge-friendly narrative" content={summary.judge_friendly_explanation} />
        <ExplanationSection label="Technical explanation" content={summary.technical_explanation} />
      </div>
    </section>
  );
};

export default ExplanationSummary;
