"""Utilities for persisting XAI artefacts to disk."""

from __future__ import annotations

import json
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Optional

from reportlab.lib.pagesizes import LETTER
from reportlab.pdfgen import canvas


@dataclass
class ArtifactPaths:
    shap_path: Optional[Path] = None
    lime_path: Optional[Path] = None
    gradcam_path: Optional[Path] = None
    similarity_path: Optional[Path] = None
    nemotron_summary_path: Optional[Path] = None
    pdf_report_path: Optional[Path] = None


def _ensure_directory(root: str | os.PathLike[str]) -> Path:
    directory = Path(root)
    directory.mkdir(parents=True, exist_ok=True)
    return directory


def _write_json(path: Path, payload: Dict[str, Any]) -> Path:
    path.write_text(json.dumps(payload, indent=2, default=str), encoding="utf-8")
    return path


def _write_text(path: Path, content: str) -> Path:
    path.write_text(content, encoding="utf-8")
    return path


def _write_placeholder_gradcam(path: Path, heatmap_payload: Dict[str, Any]) -> Path:
    """Persist a Grad-CAM heatmap.

    The placeholder writes metadata as JSON until actual heatmap generation is implemented.
    """

    if "image" in heatmap_payload:
        del heatmap_payload["image"]
    return _write_json(path, heatmap_payload)


def _write_pdf_report(path: Path, content: Dict[str, Any]) -> Path:
    """Generate a simple PDF report summarising XAI artefacts."""

    buffer = canvas.Canvas(str(path), pagesize=LETTER)
    width, height = LETTER
    x_margin = 72
    y = height - 72

    buffer.setFont("Helvetica-Bold", 16)
    buffer.drawString(x_margin, y, content.get("title", "XAI Report"))
    y -= 32

    buffer.setFont("Helvetica", 10)
    buffer.drawString(x_margin, y, content.get("subtitle", "Generated by BXAI"))
    y -= 24

    buffer.setFont("Helvetica", 11)
    for line in content.get("lines", []):
        if y < 72:
            buffer.showPage()
            buffer.setFont("Helvetica", 11)
            y = height - 72
        buffer.drawString(x_margin, y, str(line))
        y -= 18

    buffer.showPage()
    buffer.save()
    return path


def save_artifacts_bundle(
    *,
    output_dir: str | os.PathLike[str],
    shap_payload: Optional[Dict[str, Any]] = None,
    lime_payload: Optional[Dict[str, Any]] = None,
    gradcam_payload: Optional[Dict[str, Any]] = None,
    similarity_payload: Optional[Dict[str, Any]] = None,
    nemotron_summary: Optional[str] = None,
    pdf_content: Optional[Dict[str, Any]] = None,
) -> ArtifactPaths:
    """Persist generated artefacts and return their file paths."""

    root = _ensure_directory(output_dir)
    paths = ArtifactPaths()

    if shap_payload is not None:
        paths.shap_path = _write_json(root / "shap_values.json", shap_payload)

    if lime_payload is not None:
        paths.lime_path = _write_json(root / "lime_output.json", lime_payload)

    if gradcam_payload is not None:
        paths.gradcam_path = _write_placeholder_gradcam(root / "gradcam.json", gradcam_payload)

    if similarity_payload is not None:
        paths.similarity_path = _write_json(root / "similarity_results.json", similarity_payload)

    if nemotron_summary is not None:
        paths.nemotron_summary_path = _write_text(root / "nemotron_summary.txt", nemotron_summary)

    if pdf_content is not None:
        paths.pdf_report_path = _write_pdf_report(root / "xai_report.pdf", pdf_content)

    return paths
